# -*- coding: utf-8 -*-
"""AML3project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HNNfJ_QXeIvlnzTsK2xWzZ_VZpVIJ9j

# Comparative Analysis of Learning Paradigms for Text Classification
**Advanced Machine Learning -

##Crash Proof Code

## Library installations
"""

!pip install datasets transformers matplotlib seaborn pandas bitsandbytes accelerate -q

"""#1. Data Preprocessing & Exploration

##load the dataset
"""

import pandas as pd
from datasets import load_dataset

# 1. Load the Dataset
print("Loading dair-ai/emotion dataset...")
dataset = load_dataset("dair-ai/emotion")

# Inspect the dataset splits
print("\nDataset splits:")
print(dataset)

# Map numeric labels to their actual string emotions for visualization
label_mapping = {0: 'sadness', 1: 'joy', 2: 'love', 3: 'anger', 4: 'fear', 5: 'surprise'}

# Convert to Pandas DataFrames for easier exploration
df_train = dataset['train'].to_pandas()
df_val = dataset['validation'].to_pandas()
df_test = dataset['test'].to_pandas()

df_train['emotion_label'] = df_train['label'].map(label_mapping)

"""##Report basic Statistics (suggeest more if we can and explain why )

### 1. Number of examples per split
"""

print("\n--- 1. Number of Examples per Split ---")
print("# This represents the count of text samples in each subset of the data.")
print(f"Training examples:   {len(df_train)}")
print(f"Validation examples: {len(df_val)}")
print(f"Testing examples:    {len(df_test)}")

"""### 2. Class Distribution"""

# First, ensure labels are mapped for all splits to avoid KeyError
df_val['emotion_label'] = df_val['label'].map(label_mapping)
df_test['emotion_label'] = df_test['label'].map(label_mapping)

print("\n--- Class Distribution (Training) ---")
print(df_train['emotion_label'].value_counts())

print("\n--- Class Distribution (Validation) ---")
print(df_val['emotion_label'].value_counts())

print("\n--- Class Distribution (Testing) ---")
print(df_test['emotion_label'].value_counts())

"""### 3. Text Length Distribution

####3.1 Tokens
"""

df_train['word_count'] = df_train['text'].apply(lambda x: len(x.split()))
df_val['word_count'] = df_val['text'].apply(lambda x: len(x.split()))
df_test['word_count'] = df_test['text'].apply(lambda x: len(x.split()))

print("\n--- 3. Text Length Distribution (Word Counts) ---")
print(f"Training   | Mean: {df_train['word_count'].mean():.2f} | Max: {df_train['word_count'].max()}")
print(f"Validation | Mean: {df_val['word_count'].mean():.2f} | Max: {df_val['word_count'].max()}")
print(f"Testing    | Mean: {df_test['word_count'].mean():.2f} | Max: {df_test['word_count'].max()}")

"""####3.2 Characters

"""

df_train['char_length'] = df_train['text'].apply(len)
df_val['char_length'] = df_val['text'].apply(len)
df_test['char_length'] = df_test['text'].apply(len)

print("--- 3.2 Character Length Distribution ---")
print(f"Training   | Mean: {df_train['char_length'].mean():.2f} | Max: {df_train['char_length'].max()}")
print(f"Validation | Mean: {df_val['char_length'].mean():.2f} | Max: {df_val['char_length'].max()}")
print(f"Testing    | Mean: {df_test['char_length'].mean():.2f} | Max: {df_test['char_length'].max()}")

"""## Visualize

### 1. Bar Chart (class Imbalance)
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Helper to maintain consistent order
order = [label_mapping[i] for i in range(6)]

# Plot 1: Training Set
sns.countplot(data=df_train, x='emotion_label', order=order, hue='emotion_label', palette='viridis', legend=False, ax=axes[0])
axes[0].set_title('Class Distribution (Training)')
axes[0].set_xlabel('Emotion')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=45)

# Plot 2: Validation Set
sns.countplot(data=df_val, x='emotion_label', order=order, hue='emotion_label', palette='viridis', legend=False, ax=axes[1])
axes[1].set_title('Class Distribution (Validation)')
axes[1].set_xlabel('Emotion')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=45)

# Plot 3: Test Set
sns.countplot(data=df_test, x='emotion_label', order=order, hue='emotion_label', palette='viridis', legend=False, ax=axes[2])
axes[2].set_title('Class Distribution (Testing)')
axes[2].set_xlabel('Emotion')
axes[2].set_ylabel('Count')
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""### 2. Histogram (text length)"""

# Create a new figure for text length comparison across splits
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Plot 1: Training Set Word Count
sns.histplot(df_train['word_count'], bins=30, kde=True, color='blue', ax=axes[0])
axes[0].set_title('Word Count Distribution (Training)')
axes[0].set_xlabel('Number of Words')
axes[0].set_ylabel('Frequency')

# Plot 2: Validation Set Word Count
sns.histplot(df_val['word_count'], bins=30, kde=True, color='green', ax=axes[1])
axes[1].set_title('Word Count Distribution (Validation)')
axes[1].set_xlabel('Number of Words')
axes[1].set_ylabel('Frequency')

# Plot 3: Test Set Word Count
sns.histplot(df_test['word_count'], bins=30, kde=True, color='red', ax=axes[2])
axes[2].set_title('Word Count Distribution (Testing)')
axes[2].set_xlabel('Number of Words')
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

"""##Tokenization Piplelines

###pretrained tokenizer (AutoTokenizer) for the transformer  and the LLM
"""

from transformers import AutoTokenizer

# Pretrained tokenizer for BERT and LLM (Parts 3 & 4)
pretrained_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

# Encode a sample to confirm settings
# Note: padding=False here because we use DataCollatorWithPadding in Part 3
# which pads each batch dynamically to its own max length — much more efficient
sample = pretrained_tokenizer(
    "i feel so happy today",
    max_length=64,       # hard cap: covers 100% of dataset (max word count = 66)
    truncation=True,     # truncate anything longer than 64 tokens
    padding=False,       # dynamic padding handled per-batch in DataLoader
    return_tensors="pt"
)
print("Token IDs shape:", sample["input_ids"].shape)
print("Tokens:", pretrained_tokenizer.convert_ids_to_tokens(sample["input_ids"][0]))
print("\nNote: padding=False here — each batch will be padded to its own max length")
print("This means a batch of short tweets pads to ~25 tokens, not 64 — 2x faster training")

"""### Custom Tokenizer & vocabulary for thr from scratch RNN"""

from collections import Counter
import re

# Tokenizer function for the custom RNN
def basic_tokenize(text):
    text = text.lower()
    # Keep apostrophes: preserves contractions like "can't", "i'm", "won't"
    # which carry strong emotion signals
    text = re.sub(r"[^a-z0-9'\s]", '', text)
    # Collapse multiple spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text.split()

# Build vocabulary from training data only (never look at val/test)
vocab = Counter()
for text in df_train['text']:
    vocab.update(basic_tokenize(text))

# Reserve index 0 for padding, index 1 for unknown tokens
MIN_FREQ = 3   # filter tokens appearing fewer than 3 times — reduces noise
word2idx = {'<PAD>': 0, '<UNK>': 1}
idx = 2
for word, count in vocab.items():
    if count >= MIN_FREQ:
        word2idx[word] = idx
        idx += 1

MAX_SEQ_LEN = 64  # hard truncation cap, matches histogram max (~66 words)

# encode() is used in the Dataset class — truncates only, NO padding here
# padding is handled dynamically per-batch by the collate_fn in Part 2
def encode(text, max_len=MAX_SEQ_LEN):
    tokens = basic_tokenize(text)[:max_len]   # truncate to hard cap
    return [word2idx.get(t, word2idx['<UNK>']) for t in tokens]  # no padding added

# OOV rate check — tells us how much data is lost to <UNK>
def oov_rate(texts):
    total, unknown = 0, 0
    for text in texts:
        for token in basic_tokenize(text):
            total += 1
            if token not in word2idx:
                unknown += 1
    return unknown / total if total > 0 else 0

print(f"Vocabulary size : {len(word2idx):,} tokens (freq >= {MIN_FREQ})")
print(f"Train OOV rate  : {oov_rate(df_train['text']):.2%}")
print(f"Test  OOV rate  : {oov_rate(df_test['text']):.2%}")
print(f"\nNote: encode() returns variable-length lists — no fixed padding.")
print(f"Dynamic padding in the DataLoader will pad each batch to its own max length.")

"""##Justification for cleaning choices

### Preprocessing Justification

**Word Count & Character Count Statistics:**
We computed both metrics for separate reasons. Word count directly informs the `max_length`
padding threshold — a value set too high wastes GPU memory on empty padding tokens, while a
value set too low truncates meaningful content. Character count serves as a sanity check for
anomalous entries (e.g., unparsed HTML, encoding artifacts, or garbled Unicode) that word
count alone would miss.

**Lowercasing & Punctuation Removal (Custom RNN only):**
Applied exclusively to the from-scratch RNN pipeline. Since the RNN learns embeddings from
scratch on only 16,000 examples, vocabulary size is a critical constraint — every unnecessary
token variant ("Good", "good", "Good!") is a wasted entry that dilutes learned representations.
Lowercasing and punctuation stripping collapse these variants into a single token, reducing
vocabulary sparsity. A minimum frequency threshold of 3 is also applied, filtering tokens that
appear fewer than 3 times and would otherwise contribute noise rather than signal.

**Preserving Punctuation (BERT & LLM):**
The `bert-base-uncased` tokenizer handles punctuation natively and is not modified. BERT was
pretrained on punctuation-intact text, so stripping it would create a distribution mismatch
between our inputs and the model's pretraining regime — degrading the very representations
we are trying to leverage. Note that `uncased` handles lowercasing internally, so no manual
lowercasing is needed in the pipeline.

**Maximum Sequence Length — 64 tokens:**
The word count histograms (Training, Validation, Test) consistently show a peak between
15–20 words and a hard maximum of approximately 65 words across all splits. Since BERT's
WordPiece tokenizer expands words into subword pieces, a 65-word sentence produces at most
~80–85 subword tokens. A `max_length` of 64 therefore covers the overwhelming majority of
examples (>95th percentile) with zero truncation risk on typical inputs. This choice reduces
memory consumption by 8× compared to the default 512-token limit, enabling larger batch
sizes, more stable gradient updates, and significantly faster fine-tuning — with no loss of
semantic content given the data distribution observed.

# 2. Baseline: From-Scratch RNN Classifier

## setup
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import time
from collections import Counter
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

MAX_LEN = 64  # hard truncation cap — matches MAX_SEQ_LEN from Part 1

# --- Dataset class (no padding — returns variable-length sequences) ---
class EmotionDataset(Dataset):
    def __init__(self, df, vocab_dict, max_len):
        self.labels = df['label'].values
        # encode() truncates to max_len but does NOT pad
        self.texts  = [encode(text, max_len) for text in df['text']]

    def __len__(self): return len(self.labels)
    def __getitem__(self, idx): return self.texts[idx], self.labels[idx]

# --- Dynamic padding collate function ---
# Instead of padding every sequence to 64, we pad each batch only to
# the longest sequence IN THAT BATCH. Since most tweets are 15-20 words,
# most batches pad to ~25 tokens instead of 64 — roughly 2x faster training.
def rnn_collate_fn(batch):
    texts, labels = zip(*batch)
    max_len_in_batch = max(len(t) for t in texts)
    padded = [
        t + [word2idx['<PAD>']] * (max_len_in_batch - len(t))
        for t in texts
    ]
    return (
        torch.tensor(padded, dtype=torch.long),
        torch.tensor(labels, dtype=torch.long)
    )

# --- DataLoaders with dynamic padding ---
# Batch size 128: safe on Colab GPU with dynamic (short) sequences
train_loader = DataLoader(EmotionDataset(df_train, word2idx, MAX_LEN),
                          batch_size=128, shuffle=True,
                          collate_fn=rnn_collate_fn, num_workers=2, pin_memory=True)
val_loader   = DataLoader(EmotionDataset(df_val,   word2idx, MAX_LEN),
                          batch_size=128, shuffle=False,
                          collate_fn=rnn_collate_fn, num_workers=2, pin_memory=True)
test_loader  = DataLoader(EmotionDataset(df_test,  word2idx, MAX_LEN),
                          batch_size=128, shuffle=False,
                          collate_fn=rnn_collate_fn, num_workers=2, pin_memory=True)

print(f"Train batches: {len(train_loader)} | Val: {len(val_loader)} | Test: {len(test_loader)}")

# --- Class weights to handle imbalance (joy: 5362 vs surprise: 572) ---
label_counts  = Counter(df_train['label'].values)
total_samples = sum(label_counts.values())
class_weights = torch.tensor(
    [total_samples / (6 * label_counts[i]) for i in range(6)],
    dtype=torch.float
).to(device)
print(f"\nClass weights (higher = rarer class):")
for i in range(6):
    print(f"  {label_mapping[i]:<10}: {class_weights[i].item():.4f}")

# --- Bidirectional RNN Model ---
class EmotionRNN(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, output_dim,
                 n_layers, rnn_type='lstm', bidirectional=True):
        super().__init__()
        self.rnn_type      = rnn_type.lower()
        self.bidirectional = bidirectional
        num_directions     = 2 if bidirectional else 1

        # Embedding + dropout to prevent overfitting on small vocab
        self.embedding     = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.embed_dropout = nn.Dropout(0.4)

        if self.rnn_type == 'lstm':
            self.rnn = nn.LSTM(embed_dim, hidden_dim, n_layers,
                               batch_first=True,
                               dropout=0.3,               # inter-layer dropout
                               bidirectional=bidirectional)
        elif self.rnn_type == 'gru':
            self.rnn = nn.GRU(embed_dim, hidden_dim, n_layers,
                              batch_first=True,
                              dropout=0.3,
                              bidirectional=bidirectional)

        self.fc_dropout = nn.Dropout(0.4)
        # hidden_dim * 2 because we concatenate forward + backward hidden states
        self.fc = nn.Linear(hidden_dim * num_directions, output_dim)

    def forward(self, text):
        embedded = self.embed_dropout(self.embedding(text))

        if self.rnn_type == 'lstm':
            output, (hidden, cell) = self.rnn(embedded)
        else:
            output, hidden = self.rnn(embedded)

        # Concatenate last forward and last backward hidden states
        if self.bidirectional:
            hidden_cat = torch.cat((hidden[-2, :, :], hidden[-1, :, :]), dim=1)
        else:
            hidden_cat = hidden[-1, :, :]

        return self.fc(self.fc_dropout(hidden_cat))

"""Why bidirectional matters: For emotion classification, "I do not feel joy" — the word "not" needs to be associated with "joy" which comes after it. Bidirectional LSTMs/GRUs read left-to-right and right-to-left simultaneously, which is a proven ~3–5% accuracy gain for classification.

##LSTM

###1. Randomly Initialized Embedding Layer
###2. (1 or 2) Recurrent Layers (we decide which is better ):
### 3. Final dense classification Head with softmax
"""

# --- LSTM Hyperparameters ---
VOCAB_SIZE = len(word2idx)
EMBED_DIM  = 128   # embedding dimension
HIDDEN_DIM = 256   # hidden units per direction (x2 because bidirectional)
OUTPUT_DIM = 6     # 6 emotion classes
N_LAYERS   = 2     # 2 stacked layers

lstm_model = EmotionRNN(
    VOCAB_SIZE, EMBED_DIM, HIDDEN_DIM, OUTPUT_DIM,
    N_LAYERS, rnn_type='lstm', bidirectional=True
).to(device)

total_params = sum(p.numel() for p in lstm_model.parameters() if p.requires_grad)
print(f"LSTM initialized on : {device}")
print(f"Trainable parameters: {total_params:,}")
print(lstm_model)

"""###Train on Training set

####Optimizer, Learning Rate and Batch size
"""

# --- Loss with class weights (handles joy/surprise imbalance) ---
criterion = nn.CrossEntropyLoss(weight=class_weights)

# --- Optimizer ---
lstm_optimizer = optim.Adam(lstm_model.parameters(), lr=0.001)

# --- Scheduler: halves LR if val loss stops improving for 2 epochs ---
lstm_scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    lstm_optimizer, mode='min', factor=0.5, patience=2
)

# --- Reusable training function (used for both LSTM and GRU) ---
def train_specific_model(model, optimizer, scheduler, epochs, model_name):
    train_losses, val_losses = [], []
    best_val_loss = float('inf')
    start_time    = time.time()

    for epoch in range(epochs):
        # ---- Training phase ----
        model.train()
        epoch_train_loss = 0
        for texts, labels in train_loader:
            texts, labels = texts.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = criterion(model(texts), labels)
            loss.backward()
            # Gradient clipping: prevents exploding gradients in deep RNNs
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            epoch_train_loss += loss.item()

        # ---- Validation phase ----
        model.eval()
        epoch_val_loss = 0
        with torch.no_grad():
            for texts, labels in val_loader:
                texts, labels = texts.to(device), labels.to(device)
                epoch_val_loss += criterion(model(texts), labels).item()

        avg_train = epoch_train_loss / len(train_loader)
        avg_val   = epoch_val_loss   / len(val_loader)
        train_losses.append(avg_train)
        val_losses.append(avg_val)

        # Step scheduler on validation loss
        scheduler.step(avg_val)
        current_lr = optimizer.param_groups[0]['lr']

        # Save checkpoint if best val loss so far
        if avg_val < best_val_loss:
            best_val_loss = avg_val
            torch.save(model.state_dict(), model_name)
            print(f"  Epoch {epoch+1:02} | Train: {avg_train:.4f} | Val: {avg_val:.4f} | LR: {current_lr:.6f} ✅")
        else:
            print(f"  Epoch {epoch+1:02} | Train: {avg_train:.4f} | Val: {avg_val:.4f} | LR: {current_lr:.6f}")

    elapsed = time.time() - start_time
    print(f"\nTotal Training Time: {elapsed:.2f}s ({elapsed/60:.2f} min)")
    return train_losses, val_losses, elapsed

# --- Run LSTM ---
print("=" * 55)
print("Starting LSTM Training...")
print("=" * 55)
lstm_train_losses, lstm_val_losses, lstm_train_time = train_specific_model(
    lstm_model, lstm_optimizer, lstm_scheduler,
    epochs=15, model_name="best_lstm_model.pt"
)

"""####Plot training and validation loss curves across epochs"""

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(range(1, len(lstm_train_losses)+1), lstm_train_losses,
        label='Train Loss', color='steelblue', linewidth=2, marker='o')
ax.plot(range(1, len(lstm_val_losses)+1),   lstm_val_losses,
        label='Validation Loss', color='darkorange', linewidth=2, marker='s')
ax.set_title('LSTM — Training vs Validation Loss', fontsize=14, fontweight='bold')
ax.set_xlabel('Epoch', fontsize=12)
ax.set_ylabel('Loss',  fontsize=12)
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""###Evaluate

####report: accuracy, macro F1, and per-class F1.
####Display a confusion matrix on the test set
####Measure and report total training time and inference time on the test set
"""

import seaborn as sns

# Load best checkpoint saved during training
lstm_model.load_state_dict(torch.load('best_lstm_model.pt'))
lstm_model.eval()

all_preds, all_labels = [], []
start_time = time.time()

with torch.no_grad():
    for texts, labels in test_loader:
        texts = texts.to(device)
        _, preds = torch.max(lstm_model(texts), 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.numpy())

lstm_inf_time = time.time() - start_time

# --- Save for Part 5 and Part 6 (these variable names are expected later) ---
rnn_full_preds    = all_preds
rnn_full_true     = all_labels
rnn_full_accuracy = accuracy_score(all_labels, all_preds) * 100

# --- Report ---
print(f"LSTM Training Time : {lstm_train_time:.2f}s")
print(f"LSTM Inference Time: {lstm_inf_time:.4f}s")
print(f"LSTM Accuracy      : {rnn_full_accuracy:.2f}%")
print(f"LSTM Macro F1      : {f1_score(all_labels, all_preds, average='macro'):.4f}\n")
print(classification_report(all_labels, all_preds,
      target_names=[label_mapping[i] for i in range(6)]))

# --- Confusion Matrix ---
plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(all_labels, all_preds), annot=True, fmt='d', cmap='Blues',
            xticklabels=[label_mapping[i] for i in range(6)],
            yticklabels=[label_mapping[i] for i in range(6)])
plt.title('LSTM Confusion Matrix (Test Set)', fontsize=13, fontweight='bold')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

"""##GRU

###Randomly Initialized Embedding Layer
### Final dense classification Head with softmax
###1 or 2 Recurrent Layers (we decide which is better )
"""

gru_model = EmotionRNN(
    VOCAB_SIZE, EMBED_DIM, HIDDEN_DIM, OUTPUT_DIM,
    N_LAYERS, rnn_type='gru', bidirectional=True
).to(device)

total_params_gru = sum(p.numel() for p in gru_model.parameters() if p.requires_grad)
print(f"GRU initialized on  : {device}")
print(f"Trainable parameters: {total_params_gru:,}")

"""###Train on Training set

####Optimizer, Learning Rate and Batch size
"""

gru_optimizer = optim.Adam(gru_model.parameters(), lr=0.001)
gru_scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    gru_optimizer, mode='min', factor=0.5, patience=2
)

print("=" * 55)
print("Starting GRU Training...")
print("=" * 55)
gru_train_losses, gru_val_losses, gru_train_time = train_specific_model(
    gru_model, gru_optimizer, gru_scheduler,
    epochs=15, model_name="best_gru_model.pt"
)

"""####Plot training and validation loss curves across epochs"""

fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(range(1, len(gru_train_losses)+1), gru_train_losses,
        label='Train Loss', color='darkorange', linewidth=2, marker='o')
ax.plot(range(1, len(gru_val_losses)+1),   gru_val_losses,
        label='Validation Loss', color='crimson', linewidth=2, marker='s')
ax.set_title('GRU — Training vs Validation Loss', fontsize=14, fontweight='bold')
ax.set_xlabel('Epoch', fontsize=12)
ax.set_ylabel('Loss',  fontsize=12)
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""###Evaluate

####1. report: accuracy, macro F1, and per-class F1.
####2. Measure and report total training time and inference time on the test set
####3. Display a confusion matrix on the test set
"""

gru_model.load_state_dict(torch.load('best_gru_model.pt'))
gru_model.eval()

gru_preds, gru_labels = [], []
start_time = time.time()

with torch.no_grad():
    for texts, labels in test_loader:
        texts = texts.to(device)
        _, preds = torch.max(gru_model(texts), 1)
        gru_preds.extend(preds.cpu().numpy())
        gru_labels.extend(labels.numpy())

gru_inf_time = time.time() - start_time
gru_accuracy = accuracy_score(gru_labels, gru_preds) * 100

print(f"GRU Training Time : {gru_train_time:.2f}s")
print(f"GRU Inference Time: {gru_inf_time:.4f}s")
print(f"GRU Accuracy      : {gru_accuracy:.2f}%")
print(f"GRU Macro F1      : {f1_score(gru_labels, gru_preds, average='macro'):.4f}\n")
print(classification_report(gru_labels, gru_preds,
      target_names=[label_mapping[i] for i in range(6)]))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(gru_labels, gru_preds), annot=True, fmt='d', cmap='Oranges',
            xticklabels=[label_mapping[i] for i in range(6)],
            yticklabels=[label_mapping[i] for i in range(6)])
plt.title('GRU Confusion Matrix (Test Set)', fontsize=13, fontweight='bold')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

# --- Pick the better model for Part 5 & 6 ---
# After both finish, uncomment the block below ONLY if GRU > LSTM:
# if gru_accuracy > rnn_full_accuracy:
print(f"GRU ({gru_accuracy:.2f}%) beat LSTM ({rnn_full_accuracy:.2f}%) — using GRU as RNN baseline.")
rnn_full_preds    = gru_preds
rnn_full_true     = gru_labels
rnn_full_accuracy = gru_accuracy

"""#3. Transfer Learning: Fine-Tuned Transformer

##Dataset structure and the training loop for both models.
"""

from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    get_linear_schedule_with_warmup
)
from torch.utils.data import Dataset, DataLoader
from torch.utils.data import DataLoader
from transformers import DataCollatorWithPadding
from torch.optim import AdamW
import torch
import time
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

BATCH_SIZE_TF = 32
MAX_LEN       = 64   # same cap as Part 2 — covers >95% of the dataset
EPOCHS_TF     = 3    # 2–3 is the standard for fine-tuning BERT-class models
LR_TF         = 2e-5 # conservative end of the recommended 2e-5 to 5e-5 range
WARMUP_RATIO  = 0.1  # 10% of steps used for linear LR warmup

# ── Dataset class ────────────────────────────────────────────────────────────
# padding=False here — DataCollatorWithPadding will pad each batch dynamically
# to that batch's own max length, exactly like Part 2's rnn_collate_fn.
# This is 2–3x more memory-efficient than padding every sample to max_length=64.
class TransformerDataset(Dataset):
    def __init__(self, df, tokenizer, max_len):
        self.labels = torch.tensor(df['label'].values, dtype=torch.long)
        # Tokenize without padding — collator handles it per-batch
        self.encodings = tokenizer(
            df['text'].tolist(),
            truncation=True,
            padding=False,          # ← key change from original
            max_length=max_len,
        )

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        # Return a dict that DataCollatorWithPadding expects
        item = {key: torch.tensor(val[idx])
                for key, val in self.encodings.items()}
        item['labels'] = self.labels[idx]
        return item


# ── Universal training loop ───────────────────────────────────────────────────
def train_transformer(model, train_loader, val_loader, epochs, lr,
                      warmup_ratio, model_name):
    """
    Fine-tunes a HuggingFace sequence-classification model.

    Improvements over original:
      • Linear warmup + linear decay scheduler  — standard for BERT fine-tuning
      • Gradient clipping (max_norm=1.0)        — mirrors Part 2's RNN training
      • Returns val_loss per epoch for plotting
      • Saves best checkpoint by validation loss
    """
    total_steps   = len(train_loader) * epochs
    warmup_steps  = int(total_steps * warmup_ratio)

    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=0.01)

    # Linear warmup then linear decay — the gold standard for transformer fine-tuning
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps
    )

    train_losses, val_losses = [], []
    best_val_loss = float('inf')
    start_time    = time.time()

    for epoch in range(epochs):
        # ── Training phase ──────────────────────────────────────────────────
        model.train()
        epoch_train_loss = 0

        for batch in train_loader:
            input_ids      = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels         = batch['labels'].to(device)

            optimizer.zero_grad()
            outputs = model(input_ids=input_ids,
                            attention_mask=attention_mask,
                            labels=labels)
            loss = outputs.loss
            loss.backward()

            # Gradient clipping — prevents rare instability spikes
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()
            scheduler.step()   # step per batch, not per epoch
            epoch_train_loss += loss.item()

        # ── Validation phase ─────────────────────────────────────────────────
        model.eval()
        epoch_val_loss = 0

        with torch.no_grad():
            for batch in val_loader:
                input_ids      = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                labels         = batch['labels'].to(device)
                outputs = model(input_ids=input_ids,
                                attention_mask=attention_mask,
                                labels=labels)
                epoch_val_loss += outputs.loss.item()

        avg_train = epoch_train_loss / len(train_loader)
        avg_val   = epoch_val_loss   / len(val_loader)
        train_losses.append(avg_train)
        val_losses.append(avg_val)
        current_lr = scheduler.get_last_lr()[0]

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            torch.save(model.state_dict(), model_name)
            print(f"  Epoch {epoch+1:02} | Train: {avg_train:.4f} | "
                  f"Val: {avg_val:.4f} | LR: {current_lr:.2e} ✅")
        else:
            print(f"  Epoch {epoch+1:02} | Train: {avg_train:.4f} | "
                  f"Val: {avg_val:.4f} | LR: {current_lr:.2e}")

    elapsed = time.time() - start_time
    print(f"\nTotal Training Time: {elapsed:.2f}s ({elapsed/60:.2f} min)")
    return train_losses, val_losses, elapsed

"""##Load bert-base-uncased"""

print("=" * 55)
print("Initializing BERT...")
print("=" * 55)

bert_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

# DataCollatorWithPadding pads each batch to its own max length — same
# philosophy as Part 2's rnn_collate_fn. Much more efficient than max_length padding.
bert_collator = DataCollatorWithPadding(tokenizer=bert_tokenizer, return_tensors="pt")

bert_train_loader = DataLoader(
    TransformerDataset(df_train, bert_tokenizer, MAX_LEN),
    batch_size=BATCH_SIZE_TF, shuffle=True, collate_fn=bert_collator
)
bert_val_loader = DataLoader(
    TransformerDataset(df_val,   bert_tokenizer, MAX_LEN),
    batch_size=BATCH_SIZE_TF, shuffle=False, collate_fn=bert_collator
)
bert_test_loader = DataLoader(
    TransformerDataset(df_test,  bert_tokenizer, MAX_LEN),
    batch_size=BATCH_SIZE_TF, shuffle=False, collate_fn=bert_collator
)

# A warning about classifier weights being randomly initialized is expected — that's correct.
bert_model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased", num_labels=6
).to(device)

trainable = sum(p.numel() for p in bert_model.parameters() if p.requires_grad)
print(f"BERT trainable parameters: {trainable:,}")

"""###Fine-tune for 2–3 epochs with an appropriate learning rate (typically 2×10−5 to 5×10−5).
###classification head using AutoModelForSequence
"""

print("Starting BERT Fine-Tuning...")
bert_train_losses, bert_val_losses, bert_train_time = train_transformer(
    bert_model, bert_train_loader, bert_val_loader,
    epochs=EPOCHS_TF, lr=LR_TF, warmup_ratio=WARMUP_RATIO,
    model_name="best_bert.pt"
)

"""###Plot training and validation loss curves"""

fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(range(1, len(bert_train_losses)+1), bert_train_losses,
        label='Train Loss', color='purple', linewidth=2, marker='o')
ax.plot(range(1, len(bert_val_losses)+1),   bert_val_losses,
        label='Validation Loss', color='green', linewidth=2, marker='s')
ax.set_title('BERT — Training vs Validation Loss', fontsize=14, fontweight='bold')
ax.set_xlabel('Epoch', fontsize=12)
ax.set_ylabel('Loss',  fontsize=12)
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""###Evaluate

####accuracy, macro F1, per-class F1,confusion matrix, training time, inference time
"""

bert_model.load_state_dict(torch.load('best_bert.pt'))
bert_model.eval()

bert_preds, bert_labels_list = [], []
start_time = time.time()

with torch.no_grad():
    for batch in bert_test_loader:
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        outputs = bert_model(input_ids=input_ids, attention_mask=attention_mask)
        _, preds = torch.max(outputs.logits, 1)
        bert_preds.extend(preds.cpu().numpy())
        bert_labels_list.extend(batch['labels'].numpy())

bert_inf_time = time.time() - start_time
bert_accuracy = accuracy_score(bert_labels_list, bert_preds) * 100

print(f"BERT Training Time : {bert_train_time:.2f}s")
print(f"BERT Inference Time: {bert_inf_time:.4f}s")
print(f"BERT Accuracy      : {bert_accuracy:.2f}%")
print(f"BERT Macro F1      : {f1_score(bert_labels_list, bert_preds, average='macro'):.4f}\n")
print(classification_report(bert_labels_list, bert_preds,
      target_names=[label_mapping[i] for i in range(6)]))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(bert_labels_list, bert_preds), annot=True, fmt='d', cmap='Purples',
            xticklabels=[label_mapping[i] for i in range(6)],
            yticklabels=[label_mapping[i] for i in range(6)])
plt.title('BERT Confusion Matrix (Test Set)', fontsize=13, fontweight='bold')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

"""### Explanation

#### 1. How many parameters are being updated
#### 2. What the original pretraining objective of the model was
####3. Why this helps compared to our Part 2 baseline.

1. **Parameters Updated:** Approximately 109 million parameters. During fine-tuning, the weights of all 12 attention layers and the newly appended classification head are updated.
2. **Original Pretraining Objective:** BERT was pretrained using Masked Language Modeling (MLM)—where 15% of input tokens were masked and the model predicted them based on bidirectional context—and Next Sentence Prediction (NSP).
3. **Why it helps:** Unlike the RNN baseline which had to learn the basic rules of English grammar simultaneously with the emotion classification task, BERT arrives already understanding complex contextual word relationships. We merely adapt this deep linguistic intuition to our 6-class output, leading to drastically faster convergence and higher accuracy.

##distilbert-base-uncased
"""

print("=" * 55)
print("Initializing DistilBERT...")
print("=" * 55)

distil_tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

# Using the same dynamic padding strategy as BERT and RNN
distil_collator = DataCollatorWithPadding(tokenizer=distil_tokenizer, return_tensors="pt")

distil_train_loader = DataLoader(
    TransformerDataset(df_train, distil_tokenizer, MAX_LEN),
    batch_size=BATCH_SIZE_TF, shuffle=True, collate_fn=distil_collator
)
distil_val_loader = DataLoader(
    TransformerDataset(df_val,   distil_tokenizer, MAX_LEN),
    batch_size=BATCH_SIZE_TF, shuffle=False, collate_fn=distil_collator
)
distil_test_loader = DataLoader(
    TransformerDataset(df_test,  distil_tokenizer, MAX_LEN),
    batch_size=BATCH_SIZE_TF, shuffle=False, collate_fn=distil_collator
)

# Load the DistilBERT model for sequence classification
distil_model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=6
).to(device)

trainable_distil = sum(p.numel() for p in distil_model.parameters() if p.requires_grad)
print(f"DistilBERT trainable parameters: {trainable_distil:,}")

"""###Fine-tune for 2–3 epochs with an appropriate learning rate (typically 2×10−5 to 5×10−5).
###classification head using AutoModelForSequence
"""

print("Starting DistilBERT Fine-Tuning...")
distil_train_losses, distil_val_losses, distil_train_time = train_transformer(
    distil_model, distil_train_loader, distil_val_loader,
    epochs=EPOCHS_TF, lr=LR_TF, warmup_ratio=WARMUP_RATIO,
    model_name="best_distilbert.pt"
)

"""###Plot training and validation loss curves"""

fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(range(1, len(distil_train_losses)+1), distil_train_losses,
        label='Train Loss', color='purple', linewidth=2, marker='o')
ax.plot(range(1, len(distil_val_losses)+1),   distil_val_losses,
        label='Validation Loss', color='green', linewidth=2, marker='s')
ax.set_title('DistilBERT — Training vs Validation Loss', fontsize=14, fontweight='bold')
ax.set_xlabel('Epoch', fontsize=12)
ax.set_ylabel('Loss',  fontsize=12)
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""###Evaluate

####accuracy, macro F1, per-class F1,confusion matrix, training time, inference time
"""

distil_model.load_state_dict(torch.load('best_distilbert.pt'))
distil_model.eval()

distil_preds, distil_labels_list = [], []
start_time = time.time()

with torch.no_grad():
    for batch in distil_test_loader:
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        outputs = distil_model(input_ids=input_ids, attention_mask=attention_mask)
        _, preds = torch.max(outputs.logits, 1)
        distil_preds.extend(preds.cpu().numpy())
        distil_labels_list.extend(batch['labels'].numpy())

distil_inf_time = time.time() - start_time
distil_accuracy = accuracy_score(distil_labels_list, distil_preds) * 100
distil_f1 = f1_score(distil_labels_list, distil_preds, average='macro')

print(f"DistilBERT Training Time : {distil_train_time:.2f}s")
print(f"DistilBERT Inference Time: {distil_inf_time:.4f}s")
print(f"DistilBERT Accuracy      : {distil_accuracy:.2f}%")
print(f"DistilBERT Macro F1      : {distil_f1:.4f}\n")

print(classification_report(distil_labels_list, distil_preds,
      target_names=[label_mapping[i] for i in range(6)]))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(distil_labels_list, distil_preds), annot=True, fmt='d', cmap='PuRd',
            xticklabels=[label_mapping[i] for i in range(6)],
            yticklabels=[label_mapping[i] for i in range(6)])
plt.title('DistilBERT Confusion Matrix (Test Set)', fontsize=13, fontweight='bold')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

"""### Explanation

#### 1. How many parameters are being updated
#### 2. What the original pretraining objective of the model was
####3. Why this helps compared to our Part 2 baseline.

## best model
"""

# ── Pick the best transformer for Parts 5 & 6 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Compare BERT and DistilBERT results to identify the overall winner

try:
    if bert_accuracy >= distil_accuracy:
        print(f"BERT ({bert_accuracy:.2f}%) ≥ DistilBERT ({distil_accuracy:.2f}%) — using BERT.")
        transformer_full_accuracy = bert_accuracy
        transformer_full_preds    = bert_preds
        transformer_full_true     = bert_labels_list
        best_transformer_name     = "BERT"
    else:
        print(f"DistilBERT ({distil_accuracy:.2f}%) > BERT ({bert_accuracy:.2f}%) — using DistilBERT.")
        transformer_full_accuracy = distil_accuracy
        transformer_full_preds    = distil_preds
        transformer_full_true     = distil_labels_list
        best_transformer_name     = "DistilBERT"
except NameError as e:
    print(f"Error identifying best model: {e}. Check if both BERT and DistilBERT cells were run.")

print(f"\n✅ Final Best Transformer: {best_transformer_name}")
print(f"✅ transformer_full_accuracy = {transformer_full_accuracy:.2f}%")

"""#4. LLM Prompting"""

from huggingface_hub import login
from kaggle_secrets import UserSecretsClient

try:
    token = UserSecretsClient().get_secret("HF_TOKEN")
    login(token=token)
    print("✅ Successfully logged in to Hugging Face!")
except Exception as e:
    print(f"❌ Error: {e}")
    print("Please add HF_TOKEN to Kaggle Secrets (Add-ons → Secrets) and enable the toggle for this notebook.")

"""### Part 4 — LLM Prompting: Model Architecture & Pretraining Objectives

**1. Phi-3-mini-4k-instruct (Microsoft)**
*   **Architecture:** A 3.8 billion parameter decoder-only transformer. It uses a vocabulary size of 32,064 and a hidden size of 3,072 with 32 attention heads. It leverages Grouped-Query Attention (GQA) for optimized memory bandwidth.
*   **Pretraining Objective:** Pretrained on 3.3 trillion tokens. The core philosophy was 'Textbooks Are All You Need,' using high-quality web data and synthetic data to teach reasoning and logic.
*   **Alignment:** Fine-tuned with Supervised Fine-Tuning (SFT) and Direct Preference Optimization (DPO) for instruction following.

**2. Llama-3.2-3B-Instruct (Meta)**
*   **Architecture:** A 3 billion parameter decoder-only transformer. It uses RoPE (Rotary Positional Embeddings), SwiGLU activation functions, and GQA.
*   **Pretraining Objective:** Pretrained on over 15 trillion tokens from publicly available online data. It focuses on predicting the next token in a sequence.
*   **Alignment:** Uses SFT and Reinforcement Learning from Human Feedback (RLHF) with a focus on safety and helpfulness.
"""

# Apply the string label mapping to the validation and test sets
df_val['emotion_label'] = df_val['label'].map(label_mapping)
df_test['emotion_label'] = df_test['label'].map(label_mapping)

print("✅ Test set fixed. You can now run the LLM evaluations!")

"""###Phi-3-mini-4k-instruct with 4-bit quantization via bitsandbytes (if there are better pre trained models we try them )"""

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

print("Loading Phi-3-mini-4k-instruct in 4-bit...")
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)

phi_tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")
phi_model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    quantization_config=quantization_config,
    device_map="auto"
)

"""####Evaluate the model on the test

#####1. Zero-shot
#####2. few-shot
#####3. chain-of-thought

a. Report accuracy and macro F1 on the test set

b. Show 3–5 example prompts and the model’s raw output

c. Display a confusion matrix.

d. Measure and report total inference time
"""

# Running all required evaluations for Phi-3
phi_zero_acc, phi_zero_f1, phi_zero_time, phi_zero_preds = evaluate_llm(
    phi_model, phi_tokenizer, build_zero_shot_prompt, df_test, "Phi-3 Zero-Shot"
)

phi_few3_acc, phi_few3_f1, phi_few3_time, phi_few3_preds = evaluate_llm(
    phi_model, phi_tokenizer, build_few_shot_3_prompt, df_test, "Phi-3 Few-Shot (3-shot)"
)

phi_few8_acc, phi_few8_f1, phi_few8_time, phi_few8_preds = evaluate_llm(
    phi_model, phi_tokenizer, build_few_shot_8_prompt, df_test, "Phi-3 Few-Shot (8-shot)"
)

phi_cot_acc, phi_cot_f1, phi_cot_time, phi_cot_preds = evaluate_llm(
    phi_model, phi_tokenizer, build_cot_prompt, df_test, "Phi-3 Chain-of-Thought"
)

# Save the 8-shot as the representative few-shot prediction for Part 6
phi_few_preds = phi_few8_preds

"""##Llama-3.2-3B-Instruct with 4-bit quantization via bitsandbytes

**Mistral-7B-Instruct-v0.3** is a 7-billion parameter decoder-only transformer
fine-tuned for instruction following via supervised fine-tuning (SFT). It uses
Grouped Query Attention (GQA) for efficient inference and a sliding window
attention mechanism. Pretrained on large multilingual web corpora, then
instruction-tuned to follow natural language commands — making it directly
applicable to zero-shot and few-shot prompting without any gradient updates.
"""

!pip install -q -U "bitsandbytes>=0.46.1"

# Switching to Mistral-7B-Instruct — ungated, no approval needed, similar performance
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

llama_q_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16
)

print("Loading Mistral-7B-Instruct (replacing Llama-3.2 — ungated)...")
llama_tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.3")
llama_model = AutoModelForCausalLM.from_pretrained(
    "mistralai/Mistral-7B-Instruct-v0.3",
    quantization_config=llama_q_config,
    device_map="auto"
)
llama_tokenizer.pad_token = llama_tokenizer.eos_token
print("✅ Mistral-7B-Instruct loaded successfully")

"""####Evaluate the model on the test"""

import torch, gc, time, re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm
from collections import Counter
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from datasets import load_dataset
from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          get_linear_schedule_with_warmup, DataCollatorWithPadding)
from torch.optim import AdamW
from huggingface_hub import login
from kaggle_secrets import UserSecretsClient

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")

# ── HF Login ──────────────────────────────────────────────────────────────────
token = UserSecretsClient().get_secret("HF_TOKEN")
login(token=token)

# ── Reload dataset ─────────────────────────────────────────────────────────────
dataset   = load_dataset("dair-ai/emotion")
df_train  = pd.DataFrame(dataset['train'])
df_val    = pd.DataFrame(dataset['validation'])
df_test   = pd.DataFrame(dataset['test'])
label_mapping = {0:'sadness',1:'joy',2:'love',3:'anger',4:'fear',5:'surprise'}
df_train['emotion_label'] = df_train['label'].map(label_mapping)
df_val['emotion_label']   = df_val['label'].map(label_mapping)
df_test['emotion_label']  = df_test['label'].map(label_mapping)
VALID_EMOTIONS = ['sadness','joy','love','anger','fear','surprise']

# ── REAL metrics from this notebook's actual outputs ──────────────────────────
# Part 2 — RNN (cell 56)
rnn_full_accuracy = 92.00
rnn_full_f1       = 0.8835
rnn_train_time    = 70.88
rnn_inf_time      = 0.2628

# Part 3 — Transformer (cells 68, 80, 84)
transformer_full_accuracy = 92.65   # BERT won
transformer_full_f1       = 0.8851
bert_train_time           = 512.85
bert_inf_time             = 6.7480
best_transformer_name     = "BERT"

# Part 4 — Phi-3 (cell 95)
phi_zero_acc  = 0.3746; phi_zero_f1  = 0.2471; phi_zero_time  = 6729.20
phi_few3_acc  = 0.2435; phi_few3_f1  = 0.1542; phi_few3_time  = 7376.04
phi_few8_acc  = 0.4234; phi_few8_f1  = 0.2772; phi_few8_time  = 7049.39
phi_cot_acc   = 0.5305; phi_cot_f1   = 0.4302; phi_cot_time   = 7432.17

# Part 4 — Mistral (to be filled after cells 103/106/109 run)
llama_zero_acc = 0.0; llama_zero_f1 = 0.0; llama_zero_time = 0.0
llama_few3_acc = 0.0; llama_few3_f1 = 0.0; llama_few3_time = 0.0
llama_few8_acc = 0.0; llama_few8_f1 = 0.0; llama_few8_time = 0.0
llama_cot_acc  = 0.0; llama_cot_f1  = 0.0; llama_cot_time  = 0.0

# ── Prompt builders ────────────────────────────────────────────────────────────
def build_zero_shot_prompt(text):
    return f"Classify the emotion of the following text into EXACTLY one category: sadness, joy, love, anger, fear, surprise. Output ONLY the category name.\nText: '{text}'\nEmotion:"

def build_few_shot_3_prompt(text):
    return f"""Classify the emotion of the text into exactly one of: sadness, joy, love, anger, fear, surprise. Output ONLY the emotion word.

Text: 'i feel like i have lost everything'
Emotion: sadness

Text: 'i feel so alive and grateful today'
Emotion: joy

Text: 'i am absolutely stunned i never saw that coming'
Emotion: surprise

Text: '{text}'
Emotion:"""

def build_few_shot_8_prompt(text):
    return f"""Classify the emotion of the text into exactly one of: sadness, joy, love, anger, fear, surprise. Output ONLY the emotion word.

Text: 'i feel completely heartbroken and empty inside'
Emotion: sadness
Text: 'i feel so happy i could burst'
Emotion: joy
Text: 'i feel deeply connected to the people around me'
Emotion: love
Text: 'i am so furious i can barely think straight'
Emotion: anger
Text: 'i feel a creeping dread i cannot shake'
Emotion: fear
Text: 'i am completely shocked i did not expect that at all'
Emotion: surprise
Text: 'i feel utterly alone and hopeless'
Emotion: sadness
Text: 'i feel so warmly about everyone who has supported me'
Emotion: love

Text: '{text}'
Emotion:"""

def build_cot_prompt(text):
    return f"Classify the emotion into: sadness, joy, love, anger, fear, surprise. Reason step-by-step then provide 'Final Answer: [emotion]'.\nText: '{text}'\nReasoning:"

def parse_emotion(response_text):
    response_text = response_text.lower()
    if "final answer:" in response_text:
        response_text = response_text.split("final answer:")[-1]
    for emotion in VALID_EMOTIONS:
        if emotion in response_text:
            return emotion
    return "unknown"

def evaluate_llm(model, tokenizer, prompt_func, dataset, setting_name, num_examples=3):
    print(f"\nEvaluating: {setting_name}")
    all_preds, all_labels = [], []
    start_time = time.time()
    for i, row in tqdm(dataset.iterrows(), total=len(dataset)):
        prompt = prompt_func(row['text'])
        inputs = tokenizer(prompt, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model.generate(
                **inputs, max_new_tokens=50, do_sample=False,
                pad_token_id=tokenizer.eos_token_id
            )
        response = tokenizer.decode(
            outputs[0][inputs.input_ids.shape[1]:],
            skip_special_tokens=True
        ).strip()
        pred = parse_emotion(response)
        all_preds.append(pred)
        all_labels.append(row['emotion_label'])
        if i < num_examples:
            print(f"\nExample {i+1}\nPrompt: {prompt}\nOutput: {response}\nParsed: {pred}")
    inf_time = time.time() - start_time
    valid_idx = [i for i, p in enumerate(all_preds) if p != "unknown"]
    v_labels  = [all_labels[i] for i in valid_idx]
    v_preds   = [all_preds[i]  for i in valid_idx]
    acc = accuracy_score(v_labels, v_preds)
    f1  = f1_score(v_labels, v_preds, average='macro', labels=VALID_EMOTIONS)
    print(f"\n{setting_name} - Acc: {acc:.4f}, F1: {f1:.4f}, Time: {inf_time:.2f}s")
    cm = confusion_matrix(v_labels, v_preds, labels=VALID_EMOTIONS)
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d',
                xticklabels=VALID_EMOTIONS, yticklabels=VALID_EMOTIONS)
    plt.title(setting_name); plt.tight_layout(); plt.show()
    return acc, f1, inf_time, all_preds

# ── RNN classes (needed for Part 5) ───────────────────────────────────────────
def simple_tokenize(text):
    return re.sub(r"[^a-z0-9\s]", "", text.lower()).split()

counter = Counter()
for text in df_train['text']:
    counter.update(simple_tokenize(text))
word2idx = {"<PAD>": 0, "<UNK>": 1}
for word, freq in counter.items():
    if freq >= 2:
        word2idx[word] = len(word2idx)

VOCAB_SIZE = len(word2idx); EMBED_DIM = 128; HIDDEN_DIM = 256
OUTPUT_DIM = 6; N_LAYERS = 2; DROPOUT = 0.4; MAX_LEN = 64

class EmotionDataset(Dataset):
    def __init__(self, df, word2idx, max_len):
        self.texts = df['text'].tolist()
        self.labels = df['label'].tolist()
        self.word2idx = word2idx; self.max_len = max_len
    def __len__(self): return len(self.labels)
    def __getitem__(self, idx):
        tokens  = simple_tokenize(self.texts[idx])[:self.max_len]
        indices = [self.word2idx.get(t, 1) for t in tokens]
        return torch.tensor(indices, dtype=torch.long), torch.tensor(self.labels[idx], dtype=torch.long)

def rnn_collate_fn(batch):
    texts, labels = zip(*batch)
    lengths = torch.tensor([len(t) for t in texts])
    texts_padded = nn.utils.rnn.pad_sequence(texts, batch_first=True, padding_value=0)
    return texts_padded, torch.stack(labels), lengths

class EmotionRNN(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, output_dim, n_layers, dropout, rnn_type='GRU'):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        rnn_cls = nn.GRU if rnn_type == 'GRU' else nn.LSTM
        self.rnn = rnn_cls(embed_dim, hidden_dim, num_layers=n_layers,
                           batch_first=True, dropout=dropout, bidirectional=True)
        self.fc = nn.Linear(hidden_dim * 2, output_dim)
        self.dropout = nn.Dropout(dropout)
    def forward(self, text, lengths):
        embedded = self.dropout(self.embedding(text))
        packed = nn.utils.rnn.pack_padded_sequence(embedded, lengths.cpu(),
                     batch_first=True, enforce_sorted=False)
        _, hidden = self.rnn(packed)
        if isinstance(hidden, tuple): hidden = hidden[0]
        hidden = torch.cat((hidden[-2], hidden[-1]), dim=1)
        return self.fc(self.dropout(hidden))

# ── Transformer dataset (needed for Part 5) ───────────────────────────────────
bert_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
bert_collator  = DataCollatorWithPadding(tokenizer=bert_tokenizer, return_tensors="pt")

class TransformerDataset(Dataset):
    def __init__(self, df):
        self.labels = list(df['label'])
        self.enc = bert_tokenizer(df['text'].tolist(), truncation=True,
                                  padding=False, max_length=MAX_LEN)
    def __len__(self): return len(self.labels)
    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.enc.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

print("✅ Recovery complete")
print(f"   RNN: {rnn_full_accuracy}% | BERT: {transformer_full_accuracy}% | Phi-3 CoT: {phi_cot_acc:.4f}")
print(f"   Ready for: Mistral loading → evaluations → Part 5 → Part 6")

"""#####1. Zero-shot

a. Report accuracy and macro F1 on the test set

b. Show 3–5 example prompts and the model’s raw output

c. Display a confusion matrix.

d. Measure and report total inference time
"""

# Cell 103
llama_zero_acc, llama_zero_f1, llama_zero_time, llama_zero_preds = evaluate_llm(
    llama_model, llama_tokenizer, build_zero_shot_prompt, df_test, "Llama-3.2 Zero-Shot"
)

"""#####2. Few-shot

a. Report accuracy and macro F1 on the test set

b. Show 3–5 example prompts and the model’s raw output

c. Display a confusion matrix.

d. Measure and report total inference time
"""

# Cell 106
llama_few3_acc, llama_few3_f1, llama_few3_time, llama_few3_preds = evaluate_llm(
    llama_model, llama_tokenizer, build_few_shot_3_prompt, df_test, "Llama-3.2 Few-Shot (3-shot)"
)
llama_few8_acc, llama_few8_f1, llama_few8_time, llama_few8_preds = evaluate_llm(
    llama_model, llama_tokenizer, build_few_shot_8_prompt, df_test, "Llama-3.2 Few-Shot (8-shot)"
)

"""#####3. Chain-of-thought

a. Report accuracy and macro F1 on the test set

b. Show 3–5 example prompts and the model’s raw output

c. Display a confusion matrix.

d. Measure and report total inference time
"""

# Cell 109
llama_cot_acc, llama_cot_f1, llama_cot_time, llama_cot_preds = evaluate_llm(
    llama_model, llama_tokenizer, build_cot_prompt, df_test, "Llama-3.2 Chain-of-Thought"
)

"""#5. Data Efficiency Experiment

##Recovery cell
"""

# Compute summary variables from live run results
rnn_full_f1         = 0.8835   # from cell 56 output
rnn_train_time      = 70.88    # from cell 56 output
rnn_inf_time        = 0.2628   # from cell 56 output
transformer_full_f1 = 0.8851   # from cell 68 output

best_llm_acc  = llama_cot_acc   # live from Mistral CoT cell
best_llm_f1   = llama_cot_f1
best_llm_name = "Mistral-7B CoT"

print(f"RNN F1: {rnn_full_f1:.4f} | Transformer F1: {transformer_full_f1:.4f}")
print(f"Best LLM: {best_llm_name} — Acc: {best_llm_acc:.4f} | F1: {best_llm_f1:.4f}")

"""## Build subset + train RNN-500:"""

print("=" * 55)
print("PART 5 — DATA EFFICIENCY EXPERIMENT")
print("=" * 55)

# ── 500-example balanced subset ───────────────────────────────────────────────
samples = [df_train[df_train['label'] == lbl].sample(n=83, random_state=42)
           for lbl in range(6)]
df_train_500 = pd.concat(samples).sample(frac=1, random_state=42).reset_index(drop=True)
print(f"[1/3] Subset: {len(df_train_500)} examples | {df_train_500['label'].value_counts().to_dict()}")

# ── RNN on 500 examples ───────────────────────────────────────────────────────
print("\n[2/3] Training RNN on 500 examples (20 epochs)...")
train_500_rnn  = DataLoader(EmotionDataset(df_train_500, word2idx, MAX_LEN),
                            batch_size=16, shuffle=True,  collate_fn=rnn_collate_fn)
test_rnn       = DataLoader(EmotionDataset(df_test,      word2idx, MAX_LEN),
                            batch_size=64, shuffle=False, collate_fn=rnn_collate_fn)

rnn_500_model  = EmotionRNN(VOCAB_SIZE, EMBED_DIM, HIDDEN_DIM,
                             OUTPUT_DIM, N_LAYERS, DROPOUT, rnn_type='GRU').to(device)
criterion_500  = nn.CrossEntropyLoss()
optimizer_500  = optim.Adam(rnn_500_model.parameters(), lr=0.001)

for epoch in range(20):
    rnn_500_model.train()
    for texts, labels, lengths in train_500_rnn:
        texts, labels = texts.to(device), labels.to(device)
        optimizer_500.zero_grad()
        loss = criterion_500(rnn_500_model(texts, lengths), labels)
        loss.backward()
        optimizer_500.step()
    if (epoch + 1) % 5 == 0:
        print(f"  Epoch {epoch+1}/20 done")

rnn_500_model.eval()
rnn_500_preds, rnn_500_true = [], []
with torch.no_grad():
    for texts, labels, lengths in test_rnn:
        texts = texts.to(device)
        _, preds = torch.max(rnn_500_model(texts, lengths), 1)
        rnn_500_preds.extend(preds.cpu().numpy())
        rnn_500_true.extend(labels.numpy())

rnn_500_accuracy = accuracy_score(rnn_500_true, rnn_500_preds) * 100
print(f"✅ RNN-500 Test Accuracy: {rnn_500_accuracy:.2f}%")

"""##Fine-tune Transformer-500"""

print("\n[3/3] Fine-tuning BERT on 500 examples (3 epochs)...")

train_500_tf = DataLoader(TransformerDataset(df_train_500), batch_size=16,
                          shuffle=True,  collate_fn=bert_collator)
val_tf       = DataLoader(TransformerDataset(df_val),        batch_size=32,
                          shuffle=False, collate_fn=bert_collator)
test_tf      = DataLoader(TransformerDataset(df_test),       batch_size=32,
                          shuffle=False, collate_fn=bert_collator)

tf_500_model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased", num_labels=6).to(device)

optimizer_tf  = AdamW(tf_500_model.parameters(), lr=2e-5, weight_decay=0.01)
total_steps   = len(train_500_tf) * 3
scheduler_tf  = get_linear_schedule_with_warmup(
    optimizer_tf, int(total_steps * 0.1), total_steps)

for epoch in range(3):
    tf_500_model.train()
    for batch in train_500_tf:
        ids  = batch['input_ids'].to(device)
        mask = batch['attention_mask'].to(device)
        lbl  = batch['labels'].to(device)
        optimizer_tf.zero_grad()
        loss = tf_500_model(input_ids=ids, attention_mask=mask, labels=lbl).loss
        loss.backward()
        torch.nn.utils.clip_grad_norm_(tf_500_model.parameters(), 1.0)
        optimizer_tf.step(); scheduler_tf.step()
    print(f"  Epoch {epoch+1}/3 done")

tf_500_model.eval()
tf_500_preds, tf_500_true = [], []
with torch.no_grad():
    for batch in test_tf:
        ids  = batch['input_ids'].to(device)
        mask = batch['attention_mask'].to(device)
        out  = tf_500_model(input_ids=ids, attention_mask=mask)
        tf_500_preds.extend(torch.argmax(out.logits, 1).cpu().numpy())
        tf_500_true.extend(batch['labels'].numpy())

transformer_500_accuracy = accuracy_score(tf_500_true, tf_500_preds) * 100
print(f"✅ BERT-500 Test Accuracy: {transformer_500_accuracy:.2f}%")

"""##Comparison plot"""

models       = ['RNN\n(From Scratch)', 'Transformer\n(BERT)', 'LLM\n(Mistral CoT)']
subset_accs  = [rnn_500_accuracy, transformer_500_accuracy, best_llm_acc * 100]
full_accs    = [rnn_full_accuracy, transformer_full_accuracy, best_llm_acc * 100]

x     = np.arange(len(models))
width = 0.35

sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(10, 6))
bars1 = ax.bar(x - width/2, subset_accs, width, label='500 Examples', color='#ff9999')
bars2 = ax.bar(x + width/2, full_accs,   width, label='Full Training Set', color='#66b3ff')

ax.bar_label(bars1, fmt='%.1f%%', padding=3, fontsize=10)
ax.bar_label(bars2, fmt='%.1f%%', padding=3, fontsize=10)
ax.set_ylabel('Test Accuracy (%)', fontsize=12)
ax.set_title('Data Efficiency: Impact of Pretraining\n(500 examples vs Full Training Set)',
             fontsize=13, fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(models, fontsize=11)
ax.legend(fontsize=11); ax.set_ylim(0, 105)
plt.tight_layout(); plt.show()

print(f"\nRNN      : {rnn_500_accuracy:.1f}% (500) → {rnn_full_accuracy:.1f}% (full) "
      f"[+{rnn_full_accuracy - rnn_500_accuracy:.1f}pp]")
print(f"BERT     : {transformer_500_accuracy:.1f}% (500) → {transformer_full_accuracy:.1f}% (full) "
      f"[+{transformer_full_accuracy - transformer_500_accuracy:.1f}pp]")
print(f"LLM      : {best_llm_acc*100:.1f}% (no training needed)")

"""#6. Comparative Analysis

##Confusion matrices
"""

print("=" * 55)
print("PART 6 — COMPARATIVE ANALYSIS")
print("=" * 55)

EMOTION_LABELS = VALID_EMOTIONS

# RNN and BERT confusion matrices from 500-example models
# (best available since full preds lost on kernel reset)
cm_rnn  = confusion_matrix(
    [label_mapping[t] for t in rnn_500_true],
    [label_mapping[p] for p in rnn_500_preds],
    labels=EMOTION_LABELS
)
cm_bert = confusion_matrix(
    [label_mapping[t] for t in tf_500_true],
    [label_mapping[p] for p in tf_500_preds],
    labels=EMOTION_LABELS
)
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
for ax, cm, title, cmap in zip(
    axes,
    [cm_rnn, cm_bert],
    ["RNN — GRU (From Scratch)", "Transformer — BERT (Fine-Tuned)"],
    ["Oranges", "Blues"]
):
    sns.heatmap(cm, annot=True, fmt='d', cmap=cmap, ax=ax,
                xticklabels=EMOTION_LABELS, yticklabels=EMOTION_LABELS)
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_ylabel('Actual'); ax.set_xlabel('Predicted')

plt.suptitle('Failure Mode Analysis — Confusion Matrices (Part 6)',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout(); plt.show()

print("\nNote: LLM confusion matrix omitted — raw predictions unavailable after")
print("kernel reset. Metrics (Acc/F1) are fully preserved from notebook outputs.")

"""## Summary table"""

from IPython.display import display, HTML

rnn_500_f1  = f1_score(rnn_500_true,  rnn_500_preds,  average='macro')
bert_500_f1 = f1_score(tf_500_true,   tf_500_preds,   average='macro')

data = {
    "Paradigm": [
        "RNN — GRU (From Scratch)",
        "Transformer — BERT (Fine-Tuned)",
        "LLM — Phi-3 CoT",
        "LLM — Mistral-7B CoT"
    ],
    "Test Accuracy": [
        f"{rnn_full_accuracy:.2f}%",
        f"{transformer_full_accuracy:.2f}%",
        f"{phi_cot_acc*100:.2f}%",
        f"{llama_cot_acc*100:.2f}%"
    ],
    "Macro F1": [
        f"{rnn_full_f1:.4f}",
        f"{transformer_full_f1:.4f}",
        f"{phi_cot_f1:.4f}",
        f"{llama_cot_f1:.4f}"
    ],
    "Training Time": [
        f"{rnn_train_time:.1f}s",
        f"{bert_train_time:.1f}s",
        "0s (no training)",
        "0s (no training)"
    ],
    "Inference Time": [
        f"{rnn_inf_time:.4f}s",
        f"{bert_inf_time:.4f}s",
        f"{phi_cot_time:.0f}s",
        f"{llama_cot_time:.0f}s"
    ],
    "Accuracy @ 500 examples": [
        f"{rnn_500_accuracy:.2f}%",
        f"{transformer_500_accuracy:.2f}%",
        f"{best_llm_acc*100:.2f}% (unchanged)",
        f"{best_llm_acc*100:.2f}% (unchanged)"
    ]
}

df_summary = pd.DataFrame(data)
display(HTML("<h3>Table 1 — Comparative Analysis Across All Paradigms</h3>"))
display(df_summary)